In [2]:
a = 1; print(type(a))

<class 'int'>


= 사용해서 변수 지정 (왼쪽: variable, 오른쪽: contents)
type: 변수의 종류 -> print: 결과 출력

In [18]:
a = 1; a = float(a); print(type(a))

<class 'float'>


a = float(a) -> print(a) => 1.0
print한 것에 대해서만 결과 출력

In [19]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


In [20]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


문자(str)도 변수에 지정할 수 있음. '' / "" 둘 다 가능
맨 앞(시작): 0, 맨 끝: -1

In [21]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


list: 나열

In [22]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


list 안에도 list 들어갈 수 있음. comma 로 분리만 하면 됨. list 하나가 한 개의 원소로 취급.
숫자도 quotation mark 넣으면 문자 취급.
문자는 결과로 출력될 때 quoatation mark 랑 같이 출력되는데, list에 있을 때는 quotation mark없이 출력

In [23]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


(): tuple
: list랑 비슷한데, 바꾸기 힘든 것?

In [24]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


{}, :로 pairwise하게 연결

In [27]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

tuple 2개가 들어 있는 list
2x3 행렬

In [28]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


numpy: 아나콘다를 다운받으면서 다운받은 폴더에 이미 numpy가 생김.
numpy를 np라고 하겠다. (as np 안 써도 됨. 안 쓰면, 밑에 있는 np를 다 다시 numpy로 바꾸면 됨.)
a.b: a 안에(under)있는 b함수를 쓰자
np.array(a): np 안에 있는 array 함수를 쓰자
array 는 matrix와 비슷
=> 결과: ndarray: n-dimension array

In [29]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


행렬끼리 곱셈할때는 size 주의 (cf)line31)

In [30]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [31]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [32]:
c*c.T

matrix([[14, 19],
        [19, 73]])

Transpose
.T 이므로 이 T는 numpy안에 있다.